name: ARM64 Build

on:
  push:
    tags:
      - 'v*-arm64'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: echo "VERSION=$(echo ${{ gitea.tag_name }} | sed 's/-arm64//')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --allow-insecure-entitlement network.host

      - name: Login to Private Registry
        uses: docker/login-action@v3
        with:
          registry: dcr.behzadan.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            dcr.behzadan.com/reza/wireguard-3proxy:latest
            dcr.behzadan.com/reza/wireguard-3proxy:${{ steps.version.outputs.VERSION }}

