name: Generic Build

on:
  push:
    tags:
      - 'v*'
    tags-ignore:
      - 'v*-arm64'
      - 'v*-amd64'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Private Registry
        uses: docker/login-action@v3
        with:
          registry: dcr.behzadan.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            dcr.behzadan.com/reza/wireguard-3proxy:latest
            dcr.behzadan.com/reza/wireguard-3proxy:${{ gitea.ref_name }}
